# Generated by Django 4.2.5 on 2023-09-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userData',
        ),
    ]
