# Generated by Django 4.2.5 on 2023-09-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hashed_pin',
            field=models.CharField(default='', max_length=128),
        ),
    ]
