# Generated by Django 4.2.5 on 2023-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='salt',
            field=models.BinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'),
        ),
    ]
