# Generated by Django 4.2.5 on 2023-09-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='site',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
