# Generated by Django 4.2.5 on 2023-09-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_userdata_email_alter_userdata_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
        migrations.AddField(
            model_name='userdata',
            name='enc_email',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='enc_password',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='enc_username',
            field=models.BinaryField(default=b''),
        ),
    ]
