# Generated by Django 4.2.5 on 2023-09-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_userprofile_salt'),
        ('manager', '0003_remove_userdata_email_remove_userdata_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.websites'),
        ),
    ]
