# Generated by Django 4.2.5 on 2023-09-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_userdata_url_websites_userdata_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='url',
            field=models.URLField(),
        ),
    ]
