# Generated by Django 4.2.5 on 2023-09-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_userprofile_salt'),
        ('manager', '0005_alter_websites_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='genSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=8)),
                ('readable', models.IntegerField(default=1)),
                ('uppercase', models.BooleanField(default=True)),
                ('lowercase', models.BooleanField(default=True)),
                ('numbers', models.BooleanField(default=False)),
                ('symbols', models.BooleanField(default=False)),
                ('separate', models.BooleanField(default=False)),
                ('words', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.userprofile')),
            ],
        ),
    ]
